### ISSUE TITLE
Unpin dependencies

### ISSUE THREAD

**Issue by IanVS** [rpl/flow-coverage-report#122]
Because this project uses pinned dependency versions, it's very likely that consumers will end up with multiple versions of various dependencies like React.  React doesn't like to have multiple versions, and in some cases this is causing me problems.  

I think it would be better to use semver and specify only the minimum required versions, and allow proper dependency resolution.  You can check in a `package.lock` or `yarn.lock` file to ensure that consistent versions are used during development, if you like.  But I don't think it's a good idea to pin dependencies as you have in your `package.json`.

**Comment by turadg** [comment]
@rpl what is your opinion on this request? Solving is as easy as merging #169

**Comment by kangax** [comment]
would love to see #169 merged; getting warnings about outdated react version in our project

**Comment by rpl** [comment]
On master all the dependencies are now unpinned  (changes introduced in #197), I'm going to release it soon as a new major release.
I'll keep this issue open until the new version has been released on npm.

**Comment by rpl** [comment]
Released on npm as part of v0.8.0
