### ISSUE TITLE
Code window very small height

### ISSUE THREAD

**Issue by darky** [rpl/flow-coverage-report#14]
Uses: 

``` css
.CodeMirror {
  height: 300px
}
```

300px very small, feel free get higher please. We need to grow here. 👆

**Comment by rpl** [comment]
@darky :+1: 
I'm going to make the html report a bit more configurable/customizable asap

**Comment by rpl** [comment]
@darky how about the new defaults introduced by #17? ;-)

**Comment by darky** [comment]
@rpl, I think, that configuration of appearance is redundantly. If it usable and conveniently by default, it makes no sense to configure it.

**Comment by rpl** [comment]
@darky it's that I prefer the previous default, but everyone else seems to prefer the source code with the auto-height, and so I will be probably the only one that will change that configurations, while the default should be ok for everyone :-)

**Comment by darky** [comment]
Small 300px height window by default? It very small and uncomfortably. I don't understand, why anybody wants rollback this...

**Comment by rpl** [comment]
Well, the new default behavior (released with the new 0.3.0 version) is that the height of the source code viewer from the HTML report (the codemirror one) is going to grow based on its content, and so it should be big enough now :-D
and no configuration is needed to achieve it ;-)
