### ISSUE TITLE
Renamed Properties

### ISSUE THREAD

**Issue by jakesyl** [rpl/flow-coverage-report#182]
Hi,

I get the following warnings when running `flow-coverage-report` from my `package.json`:
```
WARN: "includeGlob" config file property has been renamed to "globIncludePatterns"
WARN: "excludeGlob" config file property has been renamed to "globExcludePatterns"
WARN: "type" config file property has been renamed to "reportTypes"
```

Is there any reason these changes haven't been made in the README? If not I can submit a PR.

**Comment by rpl** [comment]
My apologies, there was already a PR open to fix the README.
Closing as fixed by #172 (now merged on master).
