### ISSUE TITLE
Meaning of 1x/2x/3x etc in HTML report

### ISSUE THREAD

**Issue by genebit** [rpl/flow-coverage-report#184]
What's the meaning of `1x`/`2x` etc. flags in the HTML report?

![Screen Shot 2019-03-18 at 4 15 37 PM](https://user-images.githubusercontent.com/13213650/54504610-346ea080-4999-11e9-9b69-967025e7ab93.png)

**Comment by jting-atlas** [comment]
As far as I can tell, this correlates with the output of `flow coverage <filename> --json` (or `--pretty`, to get pretty-printed readable json output)., independent of the `flow-coverage-report` frontend wrapping around the underlying `flow coverage` call.

For example, the `--pretty` JSON output contains the properties:
```
{
  "uncovered_count": 6,
  "uncovered_locs": [
    ...
    {
      "source": <full path to file>,
      "type": <type of file, e.g. SourceFile,
      "start": {"line": <line number>, "column": <col number>, "offset": <offset?>},
      "end": {"line": <line number>, "column": <col number>, "offset": <offset?>,},
    }
    ...
  ]
}
```

I think your original question highlights a related and distinct potential bug in this repo - if you were to run `flow coverage <file> --pretty` on the file you included a screenshot of, IIUC it should break up `line 14` in to 6 distinct sections, making it clearer what the 6x actually means - by highlighting the entire section within the brackets, it's become less clear.

**Comment by juicetin** [comment]
As far as I can tell, this correlates with the output of `flow coverage <filename> --json` (or `--pretty`, to get pretty-printed readable json output)., independent of the `flow-coverage-report` frontend wrapping around the underlying `flow coverage` call.

For example, the `--pretty` JSON output contains the properties:
```
{
  "uncovered_count": 6,
  "uncovered_locs": [
    ...
    {
      "source": <full path to file>,
      "type": <type of file, e.g. SourceFile,
      "start": {"line": <line number>, "column": <col number>, "offset": <offset?>},
      "end": {"line": <line number>, "column": <col number>, "offset": <offset?>,},
    }
    ...
  ]
}
```

I think your original question highlights a related and distinct potential bug in this repo - if you were to run `flow coverage <file> --pretty` on the file you included a screenshot of, IIUC it should break up `line 14` in to 6 distinct sections, making it clearer what the 6x actually means - by highlighting the entire section within the brackets, it's become less clear.
