### ISSUE TITLE
license issue - org doesn't support Mozilla Public License :-(

### ISSUE THREAD

**Issue by thejohnbackes** [rpl/flow-coverage-report#19]
Hi,
I was trying to implement your amazing package, but I've run into a bit of problem internally with the license. 
It looks like we don't support the Mozilla Public License, and that's turning out to be a real blocker for me :-(
I think I would have more luck using your package internally if the license were one of these:

- Apache 2.0 License
- BSD "2-clause" or "Simplified" License
- BSD "3-clause" License
- MIT License
- Code Project Open License 1.02
- Microsoft Public or "Permissive" License
- PostgreSQL License
- Scala License
- zlib/libpng License
- ISC
- WTFPL (slightly offensive)
- Public Domain Dedication
- The Unlicense
- Creative Commons Attribution License (but NOT other Creative Commons licenses such as ShareAlike and Noncommercial)

Any help or consideration you could offer would be appreciated! I'd love to have the ability to use your package here at LinkedIn!

- John

#1

**Comment by rpl** [comment]
Hi @thejohnbackes 
I'd really like to make you (and everyone) able to use this tool, and I don't have any problem in changing the license of this npm package (e.g. into an Apache 2.0 or MIT or BSD License).

I'm not a lawyer, but I'm wondering:

how the MPL-2.0 can introduce such a licensing issue?
especially if the software itself is not "linked together to another project sources" (in other words "is not used as a library") but only used as an external executable that produce an output (the flow coverage report) from a bunch of source files (the external project sources), at least ideally, this kind of usage shouldn't introduce any licenses compatibility issues 
(e.g. GCC itself is licensed as GPLv3, but nevertheless you can build software with it that is not covered by the same license, even proprietary software, if you are using it as the command line compiling tool, while you have to use a compatible license if you are building a new compiler of top of it).

**Comment by thejohnbackes** [comment]
I get what you're saying and that seems to make sense. the problem is more
that we have a specific list of licenses that are white listed (for npm
specifically). our system checks their existence before putting them into
the private npm repository. #bigcompanyproblems

**Comment by rpl** [comment]
@thejohnbackes hehehe, the machines are already taking over :-)

anyway, I understand and, at least if no one of the existent users have any specific issue with the new license, I'm going to change it to MIT in the next released version.

**Comment by thejohnbackes** [comment]
@rpl that's good news! thanks for the help, Luca!

**Comment by rpl** [comment]
@thejohnbackes I've just merged #23 which changes the license of the flow-coverage-report npm package into MIT, and it has been released on npm as flow-coverage-report v.0.3.0.

**Comment by thejohnbackes** [comment]
Amazing, thanks Luca!
