### ISSUE TITLE
include covered_locs in json output

### ISSUE THREAD

**Issue by clarkbw** [rpl/flow-coverage-report#20]
Hello! Awesome project!  I'm not sure how you can work using Flow without this.

I've been trying to upload the coverage reports to http://codecov.io/ so we can get some additional reporting on our coverage over time.  The @codecov team has been really helpful but one thing is missing from the generated report.

There is `uncovered_locs` but no inverse for `covered_locs`, only the sum `covered_count` which doesn't make is possible for them to create the line-by-line report.  The flow report only shows lines *not* covered and therefore Codecov will never know when lines are so it is always resulting in 0% coverage.

Can `covered_locs` be added to the output?  

I searched but couldn't find any previous mention of `covered_locs` in issues or code.  I could try to take a look if I knew where to get started.  I'm happy to sit down and pair on this as well.

**Example**

Oh yeah, here's an example coverage file from our project just in case its useful:
https://codecov.s3.amazonaws.com/v4/raw/2017-01-11/AAA12261C5E4BE20272185677850291B/a1ff5a7fc828aa85277cb09a5e534eb4a699960c/d74f9f70-e1c8-469d-8f37-6cf4e1afe8eb.txt

You have to scroll down to:

`# path=/tmp/circle-junit.qhJLwiZ/flow-coverage/flow-coverage.json`

Thank you! 

😃

**Comment by clarkbw** [comment]
Ok, I just figured out that this is actually a flow related issue with the `coverage` command.

🙇

**Comment by rpl** [comment]
Hi @clarkbw 

> Hello! Awesome project! I'm not sure how you can work using Flow without this.

I'm really glad to hear that! 
when I started to work with flow, I wanted to be able to "see" what "flow is going to miss". 
(and then I started this project and I chose 3 initial target projects: web-ext, debugger.html and browserhtml :-))

> I've been trying to upload the coverage reports to http://codecov.io/ so we can get some additional 
> reporting on our coverage over time. The @codecov team has been really helpful but one thing is 
> missing from the generated report.

This is a great news! recently I was doing some thinking exactly about that, "keep track of the flow coverage trends" over the time, and one of the options that I'm evaluating is going to involve the generation of a "fake" lcov file, how that sounds to you?

> Ok, I just figured out that this is actually a flow related issue with the coverage command.

That's true, the "flow coverage" command currently provides only the `uncovered_locs` array (and these not better specified `covered_count` and `uncovered_count`, that doesn't look to be lines, probably expressions, I have to look deeply into this).

What I'm experimenting (and planning to include asap) is to collect some "lines"-oriented stats (total lines in the file,  the number of the "not-uncovered" lines, the array of the "line ranges" that are not included in any uncovered_locs) and, using this new data, I'm planning to optionally generate a file in the [lcov format](http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php)

I think that this approach should also make it simpler for the @codecov guys

Let me know if this approach can be helpful!

it would be awesome to be able to mark a pull request with a failure when the flow-coverage goes down, we (@ mozilla/web-ext) would really love this feature :-)

**Comment by clarkbw** [comment]
Oh awesome!  That would be great!  I don't know much about the lcov format. 

I looked into the flow coverage command and made a PR here https://github.com/facebook/flow/pull/3231 I don't know if that will help you. I'm hoping it gets the data we need.

**Comment by rpl** [comment]
@clarkbw That's amazing! facebook/flow#3231 would definitely help a lot!
