### ISSUE TITLE
NaN in text report

### ISSUE THREAD

**Issue by GillesDebunne** [rpl/flow-coverage-report#57]
If a file with no type at all, `flow-coverage-report` returns this result line:
```
src/url.js                          │   NaN % │     7 │       0 │         7
```

I first thought it was a division by 0, but then realised that's the other way around.

Maybe unrelated, but when I then try to generate an html report, I get:
```
(node:54292) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Missing percent in coverageData
(node:54292) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

For reference, here is the content of the `src/url.js` file:
```
// @flow

const url: any = window.URL || window.webkitURL || window.mozURL

export default url
```

**Comment by rpl** [comment]
A fix for this issue has been merged in #61 and release on npm in the new version 0.4.0

Feel free to re-open if you are still experiencing this issue.
