### ISSUE TITLE
Track find-package-json bug

### ISSUE THREAD

**Issue by ryan953** [rpl/flow-coverage-report#83]
I should've opened a bug before. But track this in this repo too:
https://github.com/3rd-Eden/find-package-json/issues/5

**Comment by ryan953** [comment]
I updated flow-annotation-check to use a different package.json helper. Can roll back that .flowconfig change after #84

**Comment by rpl** [comment]
:+1: Thanks @ryan953!
I removed the unused ignore patter from the flow config as part of #84 (feb85f9).
