### ISSUE TITLE
Escape special shell characters in filenames

### ISSUE THREAD

**Issue by ryan953** [rpl/flow-coverage-report#92]
I just noticed that flow-coverage-report isn't escaping special chars, and it causes the check to fail. 

Without the escaping we're basically asking flow for the ast of some other file:
```
"error":{"killed":false,"code":10,"signal":null,"cmd":"flow ast /path/to/file-with--a-slash.js"},"stdout":"","stderr":"File not found: /path/to/file-with--a-slash.js\n"}
```
Should be `file-with-\-a-slash.js`

I added some fixtures to flow-annotation-check and a little method to help out, here's how it looks:
![screen shot 2017-06-08 at 6 04 15 pm](https://user-images.githubusercontent.com/187460/26956768-214f6994-4c75-11e7-8844-d19686452fae.png)

**Comment by rpl** [comment]
fixed in #100
