### ISSUE TITLE
Configuration error: ERROR: No glob has been specified.

### ISSUE THREAD

**Issue by koko236** [rpl/flow-coverage-report#94]
I just installed the module globally. When I run:
`flow-coverage-report report -i "src/**/*.js"`
straight from the examples (which happens to match my dir structure) I get:
`Configuration error: ERROR: No glob has been specified.`

Am I doing something stupid here?

**Comment by rpl** [comment]
@koko236 no, unfortunately it is something stupid, but something that I did ;-) 
the flow-coverage-report command line syntax do not need the additional "report" parameter as currently described in the usage info (and it also makes the flow-coverage-report command unable to detect the other options correctly :-( ).

I'm duping this issue with #93 which contains a fix for this.

In the meantime, you can use the following syntax which works as expected: `flow-coverage-report -i "src/**/*.js"`

**Comment by koko236** [comment]
Thanks, it works as  intended without the `report` cmd.  :-)
